### ISSUE TITLE
Title: useAnimatedGestureHandler incompatibility with react-native-reanimated v4

### ISSUE THREAD

**Issue by Elham-EN** [entropyconquers/react-native-reanimated-dnd#72]
**Bug Report**
Library version: react-native-reanimated-dnd@1.1.0
React Native Reanimated version: 4.1.6
React Native: 0.81.5
Expo SDK: 54

**Description**
SortableItem (and the underlying useSortable hook) crashes at runtime when used with react-native-reanimated v4 because useAnimatedGestureHandler was removed in that version.

**Error**

TypeError: 0, _reactNativeReanimated.useAnimatedGestureHandler is not a function (it is undefined)
Steps to Reproduce
Install react-native-reanimated-dnd@1.1.0 into a project using react-native-reanimated >= 4.0.0
Render a <Sortable> with <SortableItem> inside
App crashes immediately on load
Root Cause
useSortable.js imports and calls useAnimatedGestureHandler from react-native-reanimated. This API was deprecated in Reanimated v3 and fully removed in v4. The replacement is Gesture.Pan() from react-native-gesture-handler used with GestureDetector.

**Expected Behaviour**
The library should work with react-native-reanimated >= 4.0.0, which is the current latest stable release and the default installed by Expo SDK 54+.

**Suggested Fix**
Replace useAnimatedGestureHandler with the new Gesture.Pan() API:

import { Gesture, GestureDetector } from 'react-native-gesture-handler';

const pan = Gesture.Pan()
  .onStart(() => { ... })
  .onUpdate((e) => { ... })
  .onEnd(() => { ... });
Also, the package ships with "type": "module" in package.json, which causes a separate Metro bundler crash (Property '_toString' doesn't exist) in React Native projects since Metro does not support ESM packages natively.

**Workaround**
Downgrade to react-native-reanimated@3.x — however this conflicts with Expo SDK 54+ which ships v4 by default.

**Comment by entropyconquers** [comment]
This incompatibility applies to the 1.1.0 implementation. v2 replaced useAnimatedGestureHandler with Gesture.Pan and GestureDetector and now declares react-native-reanimated >=4.2.0 plus react-native-worklets >=0.7.0 as peer dependencies. The migration landed in commit 9c3c67d and is present on v2.1.

The current example app runs React Native 0.83.2, Reanimated 4.2.1, Worklets 0.7.2, and Expo 55. I revalidated the Draggable, vertical Sortable, horizontal Sortable, and grid flows on the iPhone 17 simulator. Closing as resolved in v2.
